version: 2.1

commands:
  setup-env:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: lein with-profile -dev,+test,+ci deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

executors:
  lein-executor:
    docker:
      - image: circleci/clojure:openjdk-8-lein-2.9.1-node
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m

jobs:
  build:
    executor: lein-executor
    steps:
      - setup-env
      - run:
          name: 'Ensure artifact isolation, inform of boxed math'
          command: lein with-profile -dev,+check check
      - run:
          name: 'Run JVM tests, reporting coverage'
          command: lein with-profile -dev,+test do clean, trampoline cloverage --lcov --junit -o coverage/
      - store_test_results:
          path: ~/repo/coverage
      - store_artifacts:
          path: ~/repo/coverage
      - run:
          name: 'Run JVM tests, under the default runner'
          command: lein with-profile -dev do clean, test
      - run:
          name: 'Run JVM tests, in a production-like setting'
          command: lein with-profile -dev,+production do clean, test
      - run:
          name: 'Compile ClojureScript test suite'
          command: lein with-profile -dev,+test do clean, cljsbuild once test
      - run:
          name: 'Run node.js tests'
          command: node target/out/tests.js
      - run:
          name: 'Compile ClojureScript test suite, in a production-like setting'
          command: lein with-profile -dev,+test do clean, cljsbuild once test-no-assert
      - run:
          name: 'Run node.js tests, in a production-like setting'
          command: node target/no-assert/out/tests.js
  deploy:
    executor: lein-executor
    steps:
      - setup-env
      - run:
          name: import GPG key
          command: echo -e "$GPG_KEY_V2" | gpg --import
      - run:
          name: Perform pre-release sanity check
          command: lein with-profile -dev,+ci run -m nedap.ci.release-workflow.api sanity-check
      - run:
          name: release to JFrog
          command: lein deploy

workflows:
  version: 2
  CircleCI:
    jobs:
      - build:
          context: JFrog
          filters:
            branches:
              only: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+(-alpha\d+)?$/
      - deploy:
          context: JFrog
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+(-alpha\d+)?$/
